- .gitmodules
- package.json
- src/routes/ProblemView.tsx
- src/routes/root.tsx
Some setup steps were specific to Linux and didn't work on Windows, so I fixed them on Windows.
> Fix setup steps on Windows

- package.json
- src/index.tsx
- Closes Issue #25 
- Deployment on sonic and local deployment work
- Checks if there's a student id after the second /
> Sonic deployment fix

- src/routes/Account.tsx
> Progress tracking Summary in the Profile page

- src/components/ResizableEditor.tsx
- src/index.css
- src/routes/Account.tsx
- src/routes/ProblemView.tsx
- src/routes/root.tsx
Related to issue #37 
- Make monaco editor window resizable
- Stop display conflict between top buttons
> Mobile view

- src/index.tsx
- src/routes/root.tsx
- extended the drawer component to add a new xl size which covers the entire screen
> Add xl size to drawer

- src/components/ProblemList.tsx
- src/routes/root.tsx
- src/types.ts
Related to issue #49 
- The problems are categorized by problem type.
- It takes in an additional parameter selectedTopic for its navbar.
> List Problems Navbar (aka New Problem List 🎉 )

- src/components/CategoryList.tsx
- src/components/ProblemList.tsx
- src/components/ProblemSearch.tsx
- src/routes/root.tsx
- added search bar to filter problems by name
- added difficulty filter
- added difficulty next to problem name
> Search and filter problems

- src/components/CategoryList.tsx
- src/components/ProblemList.tsx
- src/routes/Account.tsx
- src/routes/root.tsx
- src/types.ts
- src/utils/getCompletedProblems.ts
- added number of questions completed next to each category
- added indicators to show if a question has been started or completed
- only the categories with search results will show up on the side
> Finish improving problem list

- public/worker.py
- src/components/CodingQuestion.tsx
- src/components/MutationQuestion.tsx
- src/index.css
- src/routes/ProblemView.tsx
Related to issue #5 
- Table with input and output textboxes generated according to how many inputs the function header takes in and how many outputs it returns.
- Run doesn't work yet but a report would be returned to the component and would display ✅ or ❌ depending on the equal. The solution output would be displayed as well.
- The progress message depends on the number of mutations in the question and how many mutants have at least 1 passing and 1 failing.
- Rows can be added until a max of 15.
> Mutation UI

- src/components/ReflectionInput.tsx
- src/components/ResizableEditor.tsx
- src/index.css
- src/routes/ProblemView.tsx
- src/routes/root.tsx
- fix code editor not resizing properly when zooming
- fix overall layout (add scrolling on overflow to main page)
- add reflection prompt when user completes a problem
- save reflection in database
> Reflection prompt

- src/components/ProblemList.tsx
- src/index.css
- src/routes/root.tsx
Related to issue #7 
- The question are now divided by question types in tabs. 
- The scrolling is done on the ProblemList. The Category name and tabs remain in place.
- Fix table rows that are supposed to be green be green.
- Make problems take the whole width in ProblemList.
> Problem list tabs

- src/components/CodingQuestion.tsx
- src/components/MutationQuestion.tsx
- src/components/ReflectionInput.tsx
- src/questions.tsx
- src/routes/ProblemView.tsx
- added questions to the reflection prompt
- updated database to store question along with answer
- fix reflection prompt not hiding when switching between problems
- added 2 second timeout when clicking run button
- added name of author to each problem
> Add questions to reflection prompt

- src/hooks/useEval.tsx
Now the total tests and passed tests makes sense for the mutation style problems in the database
> Fix mutation results storing in the database

- src/routes/Account.tsx
- src/routes/Auth.tsx
- fix login page appearing when refreshing on profile page
- fix overflow with progress and reflections on profile page
- replace pfp element with Avatar component
> Small fixes

- package-lock.json
- package.json
- src/routes/Account.tsx
Added a graph tab which tracks your activity on the website by graphing the number of submissions you made by the days you made them
> Activity graph in profile page

- src/components/CategoryList.tsx
- src/index.css
- src/routes/ProblemView.tsx
Related to issue #84 
- Make it navigable when in a problem
- Only navigates through the chosen category
- Mutation and Haystack are considered categories in this case.
> Navigate through problems

- src/components/CategoryList.tsx
- src/components/ProblemList.tsx
Unlocks problems once 5 problems in the previous category are solved
> Problem locking

- src/routes/Account.tsx
- src/types.ts
- src/utils/capitalizeString.ts
- src/utils/getCategoryList.ts
- src/utils/getCompletedProblems.ts
- added a list of all the completed problems under each category in the progress view
- added the contract modal in the profile page with placeholder values
> Contract UI

- src/components/CodingQuestion.tsx
- src/components/MainTutorial.tsx
- src/components/MutationQuestion.tsx
- src/components/MutationTutorial.jsx
- Press Alt + Enter to run (I tried Ctrl + Enter but it doesn't work with the code editor)
- Added info to both tutorials
> Keyboard shortcuts

- src/components/CategoryList.tsx
- src/components/ProblemList.tsx
- src/hooks/useEval.tsx
- src/routes/root.tsx
- src/types.ts
- src/utils/categorizeCategories.ts
- src/utils/getCompletedProblems.ts
Related to issue #85 
- All Mutation and Haystack questions are regrouped into their own categories
- They have their own sub-categories and they are generalized to String, List, and Logic
- Use newly added question_type in submission table to distinguish categories and question types
> Mutation& Haystack and their sub categories

- src/routes/Account.tsx
- src/types.ts
Store contract information in the database and display latest user's contract
> Contract backend

- src/components/MainTutorial.tsx
- src/components/MutationQuestion.tsx
- Set mutation questions' rows to default 5 instead of 1
- Change tutorial's wording
> Sprint2 pr fixes

- public/worker.py
- src/components/MutationQuestion.tsx
- The SyntaxErrors are now displayed on the Solution output box
> SyntaxError display

- src/components/profile/progress/ActivityGraph.tsx
- src/routes/Account.tsx
- Added another line to the graph representing the cumulative completed submissions 
- Made it so the graph only tracks data from the past 30 days so it doesn't overcrowd
> Modify Graph data

- src/components/profile/UserInfo.tsx
The avatar was trying to find the first character in the user's username but new users don't have usernames so the application crashes.
> gave default values to newly created users

- src/components/profile/contract/ContractEdit.tsx
- fixed the layout of the coding question inputs by making it a table
> Format inputs in contract

- src/routes/root.tsx
- Fix problem with haystack category crashing
> Haystack fix

- src/components/CategoryListItem.tsx
- src/components/ProblemList.tsx
- fix contract progress showing 0 when contract doesn't exist
- removed progress when not logged in
- display number of problems found for current search query
> Fix progress based on contract

- public/worker.py
- src/routes/ProblemView.tsx
Integrated haystack problems and remove test cases display for haystack problems
> Remove test cases for Haystack Problems

- src/components/ProblemList.tsx
- src/index.css
- src/routes/root.tsx
Related to issue #121 
- ProblemList is now adapted for mobile
> Mobile problem list fix

- public/worker.py
- src/hooks/useEval.tsx
Add documentation to useEval and worker.py files
> Document backend

- README.md
- src/components/CategoryList.tsx
- src/components/ProblemList.tsx
- src/components/profile/contract/Contract.tsx
- src/components/profile/contract/ContractText.tsx
- src/error.tsx
- src/routes/Account.tsx
- src/routes/Auth.tsx
- src/routes/root.tsx
- src/setup.test.ts
- src/utils/CategoryLock.ts
- src/utils/capitalizeString.ts
- src/utils/categorizeCategories.ts
- src/utils/getCategoryList.ts
- src/utils/getCompletedProblems.ts
- src/utils/getProblemSet.ts
- src/utils/mapMutantResults.ts
- src/utils/sortProblems.ts
- add comments to code
- update readme to include info about environment variables
> Document code
